---
kind: pipeline
name: success
when:
  event: [ push ]

steps:
  - name: build
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "sucessfully built"
    depends_on:
      - clone

  - name: unit test
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "running unit tests"
      - sleep 1
      - echo "unit tests succeeded"
    depends_on:
      - clone

  - name: integration test
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "running integration tests"
      - sleep 5
      - echo "integration tests succeeded"
    depends_on:
      - clone

  - name: component test
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "running component tests"
      - sleep 15
      - echo "component tests succeeded"
    depends_on:
      - clone

  - name: e2e test
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "running e2e tests"
      - sleep 30
      - echo "e2e tests succeeded"
    depends_on:
      - clone

---
kind: pipeline
name: virtual errors
when:               # Only run the pipeline when it's a push to master
  event: [ push ]

steps:
  - name: verify docs
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "please run prettier:docs to fix this issue"
      - exit 1
    depends_on:
      - clone

  - name: slack error
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "slack server error"
      - exit 2
    depends_on:
      - clone

  - name: connection refused
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "samizdat ECONNREFUSED"
      - exit 3
    depends_on:
      - clone


  - name: merge conflict
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo "Automatic merge failed; fix conflicts in your git branch"
      - exit 4

    depends_on:
      - clone

  - name: yarn dependencies
    image: alpine:latest@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
    commands:
      - echo 'Couldn\'t find any versions for "react"'
      - exit 5
    depends_on:
      - clone
---
kind: pipeline
name: webhook

steps:
  - name: webhook
    image: plugins/webhook
    failure: ignore
    settings:
      username: myusername
      password: mypassword
      urls: https://drone-ci-butler.ngrok.io/hooks/drone
      skip_verify: true
      debug: true
