---
kind: pipeline
type: docker
name: success

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "build"
  - sleep 1
  when:
    event:
    - push

- name: unit tests
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "unit tests"
  - sleep 2
  when:
    event:
    - push

- name: integration tests
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "integration tests"
  - sleep 5
  when:
    event:
    - push

- name: component tests
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "component tests"
  - sleep 10
  when:
    event:
    - push

- name: functional tests
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "functional tests"
  - sleep 15
  when:
    event:
    - push

- name: e2e tests
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "e2e tests"
  - sleep 30
  when:
    event:
    - push

---
kind: pipeline
type: docker
name: error

platform:
  os: linux
  arch: amd64

steps:
- name: slack server error
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "slack server error"
  - echo -e ''
  - exit 1
  when:
    event:
    - push

- name: verify docs
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "verify docs"
  - echo -e 'please run prettier:docs to fix this issue'
  - exit 1
  when:
    event:
    - push

- name: connection refused
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "connection refused"
  - echo -e 'samizdat ECONNREFUSED'
  - exit 1
  when:
    event:
    - push

- name: merge conflict
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "merge conflict"
  - echo -e 'Automatic merge failed; fix conflicts in your git branch'
  - exit 1
  when:
    event:
    - push

- name: yarn dependencies
  pull: if-not-exists
  image: python:3.7-alpine@sha256:deaefc5e07ef1f3420411dd5225b2fc2ab23ae7731e8cb216d9fe74557d81db5
  commands:
  - echo -e "yarn dependencies"
  - echo -e 'Couldn'"'"'t find any versions for "react"'
  - exit 1
  when:
    event:
    - push

---
kind: pipeline
type: docker
name: webhooks

platform:
  os: linux
  arch: amd64

steps:
- name: webhook
  image: plugins/webhook
  settings:
    debug: true
    password: mypassword
    skip_verify: true
    urls: https://drone-ci-butler.ngrok.io/hooks/drone
    username: myusername
  failure: ignore

...
