---
kind: pipeline
name: test
when:               # Only run the pipeline when it's a push to master
  event: [ push ]


steps:
  - name: build
    image: alpine:latest
    commands:
      - apk update
      - echo "sucessfully built"
    depends_on:
      - clone

  - name: unit test
    image: alpine:latest
    commands:
      - echo "running unit tests"
      - sleep 1
      - echo "unit tests succeeded"
    depends_on:
      - clone


  - name: integration test
    image: alpine:latest
    commands:
      - echo "running integration tests"
      - sleep 5
      - echo "integration tests succeeded"
    depends_on:
      - clone

  - name: component test
    image: alpine:latest
    commands:
      - echo "running component tests"
      - sleep 15
      - echo "component tests succeeded"
    depends_on:
      - clone


  - name: e2e test
    image: alpine:latest
    commands:
      - echo "running e2e tests"
      - sleep 30
      - echo "e2e tests succeeded"
    depends_on:
      - clone
